THEMOVIEDB_API_URL = "https://api.themoviedb.org/3/"
THEMOVIEDB_API_KEY = "e74c8efbe10ffa1db948010a986c9ba8"

# TODO Agrupar mejor las constantes. Probablemente englobarlas en una clase general
CONFIG_ENDPOINT = "configuration"
GENRES_MOVIES_ENDPOINT = "genre/movie/list"
GENRES_TV_ENDPOINT = "genre/tv/list"
DISCOVER_MOVIE_ENDPOINT = "discover/movie"
DISCOVER_TV_ENDPOINT = "discover/tv"
FIND_EXTERNAL_ENDPOINT = "find/"
MOVIE_ENDPOINT = "movie/"
TV_ENDPOINT = "tv/"
MOVIE_IMAGE_ENDPOINT = "/images"
TV_IMAGE_ENDPOINT = "/images"
IMAGE_SIZE = "w780"